#配置连接数据库参数
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.175.131:3307/xinlvyao?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: root
#关联mapper下的*.xml配置文件
mybatis:
  mapper-locations: classpath:mapper/*.xml