spring:
  #视图解析器
  mvc:
    view:
      prefix: /pages/
      suffix: .html
  #关联redis配置文件
  profiles:
    active: redis
  cloud:
    nacos:
      discovery:
        #nacos注册中心的地址
        server-addr: localhost:8848
  #当前服务应用名称
  application:
    name: seckill-web