spring:
  rabbitmq:
    host: 192.168.175.131
    port: 5672
    username: admin
    password: admin
  profiles:
    active: redis,mapper
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  application:
    name: rabbitmq-receive
server:
  port: 8082